[build]
  command = "npm run build:web"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

# Domain redirection rules - Railway backend
[[redirects]]
  from = "/api/*"
  to = "https://illustrious-benevolence-production.up.railway.app/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/health"
  to = "https://illustrious-benevolence-production.up.railway.app/health"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  API_URL = "https://agrof.farm/api"
