version: '3.8'

services:
  # Flask API
  api:
    build:
      context: .
      target: development
    ports:
      - "5000:5000"
    environment:
      - MODEL_CKPT=artifacts/best.pt
      - FLASK_ENV=development
      - FLASK_DEBUG=true
      - PORT=5000
      - HOST=0.0.0.0
      - LOG_PREDICTIONS=false
    volumes:
      - ./artifacts:/app/artifacts
      - ./uploads:/app/uploads
      - ./data:/app/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: ngrok for mobile testing
  ngrok:
    image: ngrok/ngrok:latest
    ports:
      - "4040:4040"
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN:-}
    command: http api:5000
    depends_on:
      - api
    profiles:
      - mobile-testing

  # Optional: Redis for caching (future enhancement)
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    profiles:
      - cache

volumes:
  redis_data:

networks:
  default:
    name: crop-ai-network
